[project]
authors = ["lorenzo <lorenzo.cerrone@uzh.ch>"]
channels = ["conda-forge"]
name = "example-versioning"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.2,<3.14"

[pypi-dependencies]
mike = ">=2.1.3, <3"
mkdocs-material = ">=9.6.9, <10"
