name: build-docs
on:
  push:
    branches:
      - master
    tags:
      - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material mike
      
      - name: Configure Git user
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      
      - name: Deploy docs
        run: |
          VERSION=$(echo $GITHUB_REF | sed 's/refs\/tags\///' | sed 's/refs\/heads\///')
          echo "Deploying version $VERSION"
          # Check if the version is a stable release
          # Meaning that starts with "v" and contains only numbers and dots
          if [[ $GITHUB_REF == refs/tags/* ]] && [[ $VERSION =~ ^v[0-9.]+$ ]]; then
            mike deploy --push --update-aliases $VERSION stable
            mike set-default --push stable
            echo "Deployed stable version"
          else
            mike deploy --push dev
            echo "Deployed development version"
          fi